# -*- mode: ruby -*-
# vi: set ft=ruby :

####################################################
## Warning!                                       ##
## ---------------------------------------------- ##
## This file is automatically generated by dirt   ##
## Please edit Dirtfile.json and run "dirt apply" ##
## to update this file.                           ##
####################################################

Vagrant.configure("2") do |config|
  # Define VM box to use
  config.vm.box = "EngageBaseBox1.2"
  config.vm.box_url = "http://code.enga.ge/EngageBaseBox_1.2.box"
  
  # Set share folder
  config.vm.synced_folder "./" , "/var/www/site/", :mount_options => ["dmode=777", "fmode=666"]

  # Use hostonly network with a static IP Address
  # and enable hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.define 'overview' do |node|
    node.vm.hostname = 'overview.local'
    node.vm.network :private_network, ip: '172.31.172.206'
    node.hostmanager.aliases = %w(www.overview.local)
  end
  config.vm.provision :hostmanager

  # Enable DNS proxy in NAT mode
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Configure Apache vhost
  config.vm.provision "shell", inline: $configure_vhost

  # Configure MySQL
  config.vm.provision "shell", inline: $configure_mysql
end

## Scripts
$configure_vhost = <<SCRIPT
vhost_config="
<VirtualHost *:80>
  ServerName overview.local
  ServerAlias www.overview.local
  DocumentRoot /var/www/site/public

  <Directory /var/www/site/public>
    EnableSendfile Off
    Options FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
  </Directory>

  <Directory />
    Options FollowSymLinks
    AllowOverride None
  </Directory>

  php_flag display_startup_errors on
  php_flag display_errors on
  php_flag html_errors on
  php_flag log_errors on
  php_value error_log  /var/log/httpd/overview-phperrors.log

  LogLevel info
  ErrorLog /var/log/httpd/overview-error.log
  CustomLog /var/log/httpd/overview-access.log combined
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost _default_:443>
  ServerName overview.local
  ServerAlias www.overview.local
  DocumentRoot /var/www/site/public

  <Directory /var/www/site/public>
    EnableSendfile Off
    Options FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
  </Directory>

  <Directory />
    Options FollowSymLinks
    AllowOverride None
  </Directory>

  php_flag display_startup_errors on
  php_flag display_errors on
  php_flag html_errors on
  php_flag log_errors on
  php_value error_log  /var/log/httpd/overview-phperrors.log

  LogLevel info
  ErrorLog /var/log/httpd/overview-error.log
  CustomLog /var/log/httpd/overview-access.log combined

  # Just use the existing dummy certificate
  SSLEngine on
  SSLCertificateFile    /etc/pki/tls/certs/localhost.crt
  SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
</VirtualHost>
</IfModule>
"

echo "$vhost_config" > "/etc/httpd/sites-available/overview.conf"
ln -fs "/etc/httpd/sites-available/overview.conf" "/etc/httpd/sites-enabled/overview.conf"
service httpd restart
SCRIPT

$configure_mysql = <<SCRIPT

Q1="CREATE DATABASE IF NOT EXISTS overview;"
Q2="GRANT USAGE ON *.* TO overview@localhost IDENTIFIED BY 'jAtqJEjDYUtz';"
Q3="GRANT ALL PRIVILEGES ON overview.* TO overview@localhost;"
Q4="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}"
mysql -uroot -proot -e "$SQL"

SCRIPT
